### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by johnpryan** [tomialagbe/flutter_ui_challenges#1]
It would be nice if these projects were free to use and modify :)

**Comment by tomialagbe** [comment]
An MIT license has been included in the project

    On ‎Tuesday‎, ‎March‎ ‎6‎, ‎2018‎ ‎03‎:‎38‎:‎50‎ ‎AM‎ ‎WAT, John Ryan <notifications@github.com> wrote:  
 
 
It would be nice if these projects were free to use and modify :)

**Comment by braulio94** [comment]
good job @tomialagbe
